import { CasePreview } from './Case';

export const data: CasePreview[] = [
    {
        id: 1,
        title: 'Экоконтроль',
        description: 'Площадки услуг по работе с септиками',
        logo: '/cases/eko-kontrol-logo.webp',
        bg: '/cases/eko-kontrol.webp',
        link: 'https://eko-kontrol.ru/',
        tags: ['Экосистема', 'PWA'],
        to: '#3975CF',
    },
    {
        id: 2,
        title: 'Asb-video',
        description: 'Сайт Московской компании с автоматизацией заявок',
        logo: '/cases/asb-video-logo.webp',
        bg: '/cases/asb-video.webp',
        link: 'https://asb-video.ru/',
        tags: ['Каталог', 'Ecommerce', 'Корпоративный'],
        to: '#137332',
    },
    {
        id: 3,
        title: '22 ARCHETYPES',
        description: 'С&nbsp;калькуляторами судьбы и&nbsp;&laquo;вау-эффектами&raquo;',
        logo: '/cases/22archetypes-logo.webp',
        bg: '/cases/22archetypes.webp',
        link: 'https://www.22archetypes.com/',
        tags: ['Лендинг', 'Иностранный', 'Экзотерика'],
        to: '#0e0e0e',
    },
    {
        id: 4,
        title: 'Аэроплан',
        description: 'Рекламное агентство',
        logo: '/cases/aeroplane-logo.webp',
        bg: '/cases/aeroplane.webp',
        link: 'https://www.aeroplane-media.ru',
        tags: ['Корпоративный'],
        to: '#385599',
    },
    {
        id: 5,
        title: 'Klumba-vrn',
        description: 'С автоматизацией и удобным расчётом времени доставки',
        logo: '/cases/klumba-vrn-logo.webp',
        bg: '/cases/klumba-vrn.webp',
        link: 'https://klumba-vrn.ru/',
        tags: ['Ecommerce'],
        to: '#cc9fa9',
    },
    {
        id: 6,
        title: 'Город детства',
        description: 'Создание платёжной системы с возможностью оплаты сертфикатом',
        logo: '/cases/gorod-logo.webp',
        bg: '/cases/gorod.webp',
        link: 'https://xn---56-6cdjehbj0gaxsnb.xn--p1ai/oplata-sertificatom',
        tags: ['Платёжка'],
        to: '#019648',
    },
];
